name: vue
run-name: ${{github.actor}}
on:
  push:
    branches:
      - lab9-mm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
