name: vue
on:
  workflow_dispatch:
  push:
    branches:
      - lab9-mm
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - lab9-mm
    paths-ignore:
      - 'docs/**'
  schedule:
    - cron: '0 8 * * 1'
env:
  AZURE_TOKEN_QA_: ${{ secrets.TOKEN_QA}}
  AZURE_TOKEN_PROD_: ${{ secrets.TOKEN_PROD}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        with:
          name: lab9-mm-artifact
          path: dist
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: linter and static type 
        run: npm run lint && npm run type-check
      - name: unit tests
        run: npm test
  deploy-QA:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download production artifacts
        uses: actions/download-artifact@v4
        with:
          name: lab9-mm-artifact
          path: dist
      - name: Installing SWA CLI
        run: npm install -g @azure/static-web-apps-cli
      - name: Deploy to QA
        run: swa deploy -n stapp-vue-qa ./dist -d $AZURE_TOKEN_QA_
  deploy-PROD:
    runs-on: ubuntu-latest
    needs: deploy-QA
    if: github.event_name == 'workflow_dispatch' 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download production artifacts
        uses: actions/download-artifact@v4
        with:
          name: lab9-mm-artifact
          path: dist
      - name: Installing SWA CLI
        run: npm install -g @azure/static-web-apps-cli
      - name: Deploy to PROD
        run: swa deploy -n stapp-vue-prod ./dist -d $AZURE_TOKEN_PROD_
