name: vue
on:
  push:
    branches:
      - lab9-mm
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - lab9-mm
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lab9-mm-artifact
          path: dist
