name: vue
on:
  push:
    branches:
      - lab9-mm
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - lab9-mm
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: github.event_name == 'push' 
        with:
          name: lab9-mm-artifact
          path: dist
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: linter and static type 
        run: npm run lint && npm run type-check
      - name: unit tests
        run: npm test

